name: "Unit Test"
description: "Run unit tests with coverage and report"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js and PNPM
      uses: ./.github/actions/install

    - name: Run tests
      shell: bash
      run: pnpm test:run

    - name: Run tests with coverage
      shell: bash
      run: pnpm test:coverage

    - name: Coverage Report as Comment
      uses: davelosert/vitest-coverage-report-action@v2
      if: github.event_name == 'pull_request'
      with:
        json-summary-path: "./coverage/coverage-summary.json"
        json-final-path: "./coverage/coverage-final.json"
