name: "TypeScript"
description: "Run TypeScript type checks"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js and PNPM
      uses: ./.github/actions/install

    - name: Run TypeScript type check
      shell: bash
      run: pnpm type-check
