name: "VRT Test"
description: "Run Visual Regression Tests with Docker caching"

runs:
  using: "composite"
  steps:
    - name: Pull VRT image
      id: pull_image
      shell: bash
      run: docker pull ghcr.io/illionillion/mermaid-editor-vrt:latest
      continue-on-error: true

    - name: Build VRT image
      if: steps.pull_image.outcome == 'failure'
      shell: bash
      run: docker build -t ghcr.io/illionillion/mermaid-editor-vrt:latest -f Dockerfile.vrt .

    - name: Push VRT image
      if: steps.pull_image.outcome == 'failure'
      shell: bash
      run: docker push ghcr.io/illionillion/mermaid-editor-vrt:latest

    - name: Build and start services
      shell: bash
      run: docker compose -f compose.vrt.ci.yml up -d

    - name: Wait for server
      shell: bash
      run: npx wait-on http://localhost:6006 --timeout 180000

    - name: Run tests in container
      shell: bash
      run: docker exec mermaid-editor-vrt pnpm test:vrt

    - name: Upload VRT diff images
      if: failure() && hashFiles('__image_snapshots__/__diff_output__/*.png') != ''
      uses: actions/upload-artifact@v4
      with:
        name: vrt-diff-images
        path: __image_snapshots__/__diff_output__/

    - name: Comment artifact link on PR
      if: failure() && hashFiles('__image_snapshots__/__diff_output__/*.png') != '' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request?.number;
          if (!pr) return;
          const runId = process.env.GITHUB_RUN_ID;
          const artifactUrl = `https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${runId}`;
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr,
            body: `❌ VRTテストが失敗しました。差分画像は [Actionsのアーティファクト](${artifactUrl}) から確認できます。`
          });
