name: "Build Storybook"
description: "Build Storybook application"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js and PNPM
      uses: ./.github/actions/install

    - name: Build Storybook
      shell: bash
      run: pnpm build-storybook
