name: "ESLint"
description: "Run ESLint checks"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js and PNPM
      uses: ./.github/actions/install

    - name: Run ESLint
      shell: bash
      run: pnpm lint
