name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  # Stage 1: Code Quality Check
  quality_check:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run quality checks
        uses: ./.github/actions/quality-check

  # Stage 2: Testing and Building (parallel, depends on quality check)
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: [quality_check]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run unit tests
        uses: ./.github/actions/unit-test

      - name: Coverage Report as Comment
        uses: davelosert/vitest-coverage-report-action@v2
        if: github.event_name == 'pull_request'
        with:
          json-summary-path: "./coverage/coverage-summary.json"
          json-final-path: "./coverage/coverage-final.json"

  e2e_test:
    name: E2E Test
    runs-on: ubuntu-latest
    needs: [quality_check]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run E2E tests
        uses: ./.github/actions/e2e-test

  vrt_test:
    name: VRT Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run VRT tests
        uses: ./.github/actions/vrt-test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [quality_check]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build applications
        uses: ./.github/actions/build
